# Generated by Django 4.2.4 on 2023-09-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_name', models.CharField(max_length=100)),
                ('rec_dec', models.CharField(max_length=100)),
                ('rec_img', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
